# Generated by Django 4.2.28 on 2026-02-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_import', models.CharField(choices=[('signaletique', 'Signalétique'), ('pricing', 'Pricing')], max_length=50)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('nombre_lignes', models.IntegerField(default=0)),
                ('nombre_succes', models.IntegerField(default=0)),
                ('nombre_erreurs', models.IntegerField(default=0)),
                ('statut', models.CharField(default='en_cours', max_length=50)),
                ('erreurs', models.JSONField(blank=True, null=True)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Log d'import",
                'verbose_name_plural': "Logs d'import",
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='Signaletique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('categorie', models.CharField(blank=True, max_length=200, null=True, verbose_name='Catégorie')),
                ('statut', models.CharField(blank=True, max_length=100, null=True, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('donnees_supplementaires', models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires')),
            ],
            options={
                'verbose_name': 'Signalétique',
                'verbose_name_plural': 'Signalétiques',
                'ordering': ['-date_creation'],
            },
        ),
    ]
