# Generated by Django 4.2.28 on 2026-02-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portefeuille cible',
                'verbose_name_plural': 'Portefeuilles cibles',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TargetPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolios.targetportfolio')),
                ('signaletique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_portfolio_items', to='portfolios.signaletique')),
            ],
            options={
                'verbose_name': 'Ligne portefeuille cible',
                'verbose_name_plural': 'Lignes portefeuille cible',
                'ordering': ['id'],
                'unique_together': {('portfolio', 'signaletique')},
            },
        ),
    ]
