# Generated by Django 4.2.28 on 2026-02-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_target_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaletique',
            name='isin',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ISIN'),
        ),
    ]
