# Generated by Django 4.2.28 on 2026-02-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_signaletique_isin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portefeuille réel',
                'verbose_name_plural': 'Portefeuilles réels',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AlterField(
            model_name='importlog',
            name='type_import',
            field=models.CharField(choices=[('signaletique', 'Signalétique'), ('pricing', 'Pricing'), ('transactions', 'Transactions')], max_length=50),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('type_operation', models.CharField(choices=[('ACHAT', 'Achat'), ('VENTE', 'Vente')], max_length=10, verbose_name='Type')),
                ('quantite', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Prix unitaire')),
                ('devise', models.CharField(default='EUR', max_length=10, verbose_name='Devise')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolios.realportfolio')),
                ('signaletique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolios.signaletique')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['date', 'id'],
            },
        ),
    ]
