# Generated by Django 4.2.28 on 2026-02-16 11:56

from django.db import migrations


def remove_actif_column(apps, schema_editor):
    """Supprimer la colonne actif si elle existe"""
    with schema_editor.connection.cursor() as cursor:
        # Vérifier si la colonne existe
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='portfolios_signaletique' 
            AND column_name='actif'
        """)
        if cursor.fetchone():
            # La colonne existe, la supprimer
            cursor.execute("ALTER TABLE portfolios_signaletique DROP COLUMN actif")


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_realportfolio_alter_importlog_type_import_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_actif_column, migrations.RunPython.noop),
    ]
