# Generated by Django 4.2.29 on 2026-03-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaletique',
            name='date_cours',
            field=models.DateField(blank=True, null=True, verbose_name='Date du cours'),
        ),
        migrations.AddField(
            model_name='signaletique',
            name='devise_prix',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Devise du prix'),
        ),
        migrations.AddField(
            model_name='signaletique',
            name='frequence_coupon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fréquence coupon'),
        ),
        migrations.AddField(
            model_name='signaletique',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Prix / Cours'),
        ),
        migrations.AddField(
            model_name='signaletique',
            name='source_prix',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Source du prix'),
        ),
    ]
