# Generated by Django 4.2.29 on 2026-03-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_signaletique_date_cours_signaletique_devise_prix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Couleur (hex)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Type d'instrument",
                'verbose_name_plural': "Types d'instruments",
                'ordering': ['ordre', 'name'],
            },
        ),
    ]
